MEMORY {
	
	ram : ORIGIN = 0x40000000, LENGTH = 4M

}

REGION_ALIAS("REGION_TEXT", ram);
REGION_ALIAS("REGION_RODATA", ram);
REGION_ALIAS("REGION_DATA", ram);
REGION_ALIAS("REGION_BSS", ram);
REGION_ALIAS("REGION_STACK", ram);
REGION_ALIAS("REGION_HEAP", ram);


